# Generated by Django 2.2.2 on 2019-07-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('wechat', models.CharField(blank=True, max_length=30, null=True)),
                ('qq', models.CharField(blank=True, max_length=20, null=True)),
                ('job_num', models.CharField(blank=True, max_length=30, null=True)),
                ('sex', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=10)),
            ],
            options={
                'db_table': 'auth_accounts',
                'ordering': ('id',),
            },
        ),
    ]
