# Generated by Django 2.2.2 on 2019-07-16 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(max_length=32)),
                ('group_type', models.CharField(choices=[('user', '部门'), ('permission', '权限组'), ('notice', '通知组')], default='user', max_length=32)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.Group')),
                ('parent_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='auth.Group')),
            ],
            options={
                'db_table': 'auth_group_profiles',
                'ordering': ('id',),
            },
        ),
    ]
